### ISSUE TITLE
ADDLW/SUBLW has no DAG pattern, inherits from wrong class

### ISSUE THREAD

**Issue by UnderwoodJM** [loganleland/llvm#1]
The code for ADDLW and SUBLW looks as follows currently:

```
def ADDLW  : I8rr<0x0,
                   (outs), (ins GR8:$src),
                   "addlw\t{$src}",
                   []>;

def SUBLW  : I8rr<0x0,
                   (outs), (ins GR8:$src),
                   "sublw\t{$src}",
                   []>;
```

The problems here are:

- No DAG pattern, so there is no matching. These instructions must be lowered manually.
- The W Register isn't implemented, so there are no DAG node... anchors? edges? I'm not too sure how LLVM refers to it. Regardless, these nodes have 1 input and 0 outputs.
- They inherit from `I8rr` instead of `I8ri`. Attempting to change it myself results in compilation errors, so @loganleland will need to fix it, since he knows what he changed to put it in.

I'll also point out that "SUBWF" and "SUBLW" are "Subtract W from the incoming data," so it looks like `W = L - W` and `d = F - W`. `W` should be `$src2`

**Comment by loganleland** [comment]
Addlw and sublw are both pseudo instructions right now and are only being used for function prologue/epilogue.
