### ISSUE TITLE
Assertion Failed in Clang

### ISSUE THREAD

**Issue by UnderwoodJM** [loganleland/llvm#4]
This assertion fails when compiling C -> ASM via Clang. Compiling C -> IR -> ASM via Clang + LLD does not produce this error. I have not applied the ASM correction script.

This error only happened when compiling `addrr.c` and `andrr.c`, so I suppose it has to do with register-register transfers specifically.

Attaching log
[addrr-a8a8be.txt](https://github.com/loganleland/llvm/files/765532/addrr-a8a8be.txt)

**Comment by loganleland** [comment]
That is peculiar. This passes and generates correct asm for me. Could you post the options in clang that you used to compile to generate the error?

**Comment by UnderwoodJM** [comment]
Ah, I forgot to post that. The text file has the command, but here it is:

`../build/bin/clang -S -target pic16 -o ./testbench_asm/andrr.s ./testbench_src/andrr.c`

I have a symlink to the test source directory since my testing directory is in the top level (out of tree)
